### ISSUE TITLE
node crashed with unhandled exception 

### ISSUE THREAD

**Issue by Ljzn** [neo-project/neo-node#159]
```
neo> 
Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: System.Threading.Tasks.Task`1[System.Threading.Tasks.VoidTaskResult]
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Neo.Network.LocalNode.<>c__DisplayClass61_0.<ConnectToPeersLoop>g__connectToPeers|0(IEnumerable`1 ipEndPoints)
   at Neo.Network.LocalNode.ConnectToPeersLoop()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted (core dumped)
```

**Comment by erikzhang** [comment]
@jsolman Can you look at this issue?

**Comment by gairom** [comment]
I get the same exception.  running dotnet-sdk-2.0.2

**Comment by erikzhang** [comment]
@jsolman I can reproduce it:

```c#
class Program
{
    public static async Task DoSometingAsync()
    {
        // do something here
    }

    static void Main(string[] args)
    {
        Task task1 = DoSometingAsync();
        Task task2 = DoSometingAsync();
        Dictionary<Task, int> d = new Dictionary<Task, int>();
        d.Add(task1, 1);
        d.Add(task2, 2);
    }
}
```

**Comment by erikzhang** [comment]
It seems the `Task` returned by an `async` method will be an instance of private type `VoidTaskResult`, which can be the duplicate keys.

**Comment by jsolman** [comment]
@erikzhang Task<VoidTaskResult> should never be a duplicate key though. It should always be comparing object references with the default equals implementation if there is a hash collision in the dictionary. Anyway, previously once the desired connections were met it didn’t clean up the completed connections until the dropping below the desired connections; maybe old versions of dotnet somehow were giving weak references for the tasks or something weird. My latest change should take care of it though.

**Comment by jsolman** [comment]
@erikzhang with my changes now it would be equivalent to the following, which should never cause the issue.

class Program
{
    public static async Task DoSometingAsync()
    {
        // do something here
    }

    static void Main(string[] args)
    {
        Task task1 = DoSometingAsync();
        Task task2 = DoSometingAsync();
        Dictionary<Task, int> d = new Dictionary<Task, int>();
        if (!task1.IsCompleted)
        {
            d.Add(task1, 1);
        }

        if (!task1.IsCompleted)
        {
            d.Add(task2, 2);
        }
    }
}

**Comment by jsolman** [comment]
Please review latest changes here: https://github.com/neo-project/neo/pull/239
