### ISSUE TITLE
通过交易ID 如何获取交易发起人的地址，How to get from which address with a txhash ?

### ISSUE THREAD

**Issue by fengshangbin** [neo-project/neo-node#189]
RPC getrawtransaction可以得到交易详情，但交易输入vin不能准确知道交易from那个地址吧，因为vin指向的交易vout也有可能输出给多个地址的多笔交易。
verification这里的值是包含from的public key，但Address和public key如何转换呢？如果是一个多签名交易verification是否会包含多个public key? 如果是多个public key应该用那个作为from?

**Comment by Cherisher** [comment]
可以获取到，vin的结构为{"txid":"xxxxxxxxxxx","vout":x}
其中x就是对应的索引，这是我们项目中的部分代码

std::string getSendAddressByVin(NeoClient &client, const std::string &tx_id, const int &vout_index)
{
    try {
        Json::Value result = client.getrawtransaction(tx_id, true);
        std::cout << result["vout"][vout_index]["address"].asString() << "\t"
                  << result["vout"][vout_index]["value"].asString() << "\t"
                  << getAssetsByType(client, result["vout"][vout_index]["asset"].asString()) << std::endl;
        return result["vout"][vout_index]["address"].asString();
    } catch (...) {
        std::cout << "bug!!!!!!!!!!!!! " << std::endl;
    }
    return "";
}
