### ISSUE TITLE
node: Make 2.10.x long term support and shift to a maintenance only, use testnet resets for NEO3.

### ISSUE THREAD

**Issue by canesin** [neo-project/neo-node#354]
Following the https://github.com/neo-project/neo/issues/727 line of thought in this issue is that while the proposed roadmap is great it is more work and limiting than we really need! **_All business need (like Nash) right now is a safe and stable NEO2_** while NEO3 is not around, **_the desirable new fancy stuff can all go directly to NEO3_**. No need to so many backporting, that will only limit NEOs speed of development and limit how bold you can be, I know NEO wants to be bold ;) .

So with love from Vienna I hope that @erikzhang consider this and talk with Hongfei:

![neo_roadmap_proposal](https://user-images.githubusercontent.com/353648/57531121-0a05e780-7339-11e9-9560-a1cce98bc515.jpg)

PS: That would also allow to release a NEO3 testnet this quarter already, that would probably speed dev and attract new people. :wink:

**Comment by vncoelho** [comment]
It looks great and precise, @canesin, I agree with the support and not accept new contracts after Q2/2020.

Canesin, maybe this ROADMAP could also come in the README.
We are currently trying to update it, please check it out:
https://github.com/neo-project/neo/pull/730

**Comment by EdgeDLT** [comment]
I like this idea. I imagine it would make existing projects on NEO 2 happier since there is less stress to migrate until they are ready, and may avoid changes that may somehow break old contracts.

**Comment by shargon** [comment]
Yes, i think exactly the same as you @EdgeDLT

**Comment by Flankarooo** [comment]
That was a great idea ^^

**Comment by jmseigneur** [comment]
Stability is important

**Comment by lock9** [comment]
@neo-project/core  is there a consensus about this?

**Comment by shargon** [comment]
Old, if remains, please re-open
