### ISSUE TITLE
attach global asset when invoke a smart contract

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/neo-node#403]
Currently, `invoke` command in neo-cli does not support adding global asset (NEO or GAS). But there are scenarios that requires this function, such as ICO mintTotken, etc. There are projects like to use neo-cli to test their smart contracts during development process.

So, can we add this support to neo-cli ?

**Comment by IsaAliev** [comment]
Any workaround found? I have the same need

**Comment by shargon** [comment]
I made a draft about this issue, the problem that I see if you want to attach 2 neo, and you have 1 neo in one wallet, and 1 neo in another wallet, what should it do?

**Comment by vncoelho** [comment]
Why it has been closed,@wanglongfei88?
The PR was not merged yet.
