### ISSUE TITLE
node: Can I install neo-cli in Ubuntu 18.04?

### ISSUE THREAD

**Issue by Thorgrlm** [neo-project/neo-node#411]
Hi, I have a raspberry Pi 3B and I think this device it's will perfect for to install the neo-cli but in the documentation I can see that work only in ubuntu 16.04, there are some way the install neo-cli in ubuntu 18.04?
thanks

**Comment by thehomosapien** [comment]
![image](https://user-images.githubusercontent.com/49546882/62918617-d4501f00-bdbd-11e9-929f-32d3685344da.png)
Hi there, I am trying to run neo-cli but blocks are syncing beyond block height 328296. whenever I run neo-cli it flashes this error. I am using Ubuntu 16.04.06 on AWS t3.2xlarge. Urgent Help Needed

**Comment by shargon** [comment]
@thehomosapien please in order to help you. Please, open a new issue, and specify your configuration, plugins, etc. and very important, the steps to reproduce the issue

**Comment by thehomosapien** [comment]
done @shargon  https://github.com/neo-project/neo-cli/issues/434

**Comment by lock9** [comment]
Hi @thehomosapien, what version of neo are you using?

**Comment by shargon** [comment]
Old, if remains, please re-open
