### ISSUE TITLE
node: Neo-cli not showing Balance and Transactions

### ISSUE THREAD

**Issue by thehomosapien** [neo-project/neo-node#442]
Hi there. We are trying to integrate NEO to our application. We are using an EC2 instance with Ubuntu 16.04 and complied the source code. We are using following plugins:

ApplicationLogs
CoreMetrics
ImportBlocks
RpcNep5Tracker
RpcSecurity
RpcSystemAssetTrackerPlugin
RpcWallet
SimplePolicyPlugin

The blocks are syncing properly and everything looks fine. But When we made a transaction to one of our addresses, it's not showing up in the wallet. We are able to check it out on https://neotracker.io

Address: ASKWaPrNmc7L6cHdpgUpywtbqcwi3hNZr8
https://neotracker.io/tx/855bec3d4dcee690ff15b7d074e55ee2d59535756652b5f1c85594511b04f9f8

Other strange thing is that it also shows that the output has been already spent. But we didn't do anything.

Address: AGQGKFJ7MTMvePZcz1KEmd9UVWzZbRsotC
https://neotracker.io/tx/9832f1918e9f56de88935a19c284211ce6167a29ea6f78711b95f63d7dda080a

We also tried to check other things but nothing seems to be working. We also reindexed the chain in hope transactions might show. But it didn't worked. Everthing is really messed up. It would be very helpful if anyone would help us to figure out what is wrong where. 
![Screenshot from 2019-08-21 11-30-48](https://user-images.githubusercontent.com/49546882/63408344-6da9b180-c40c-11e9-9e7c-c787f1c7bfb4.png)
![Screenshot from 2019-08-21 11-22-29](https://user-images.githubusercontent.com/49546882/63408346-6da9b180-c40c-11e9-9059-979b923150bd.png)
![Screenshot from 2019-08-21 11-18-18](https://user-images.githubusercontent.com/49546882/63408347-6e424800-c40c-11e9-89c8-4bcb290b2211.png)

**Comment by kokahunter** [comment]
Hey @thehomosapien,

>There are bots looking for open RPC nodes with opened wallets that transfer funds out. Whitelist IPs if you need to use RPC for some reason. https://docs.neo.org/en-us/node/cli/latest-version/api.html

_Originally posted by @fabwa in https://github.com/neo-project/neo/issues/178#issuecomment-492788576_

You may also want to check the RpcSecurity configuration.

**Comment by thehomosapien** [comment]
@kokahunter , ok got that point and I will block access from all IPs expect mine. But why it isn't showing transactions. logically I should get how much I received and how much was sent out.

**Comment by kokahunter** [comment]
What is the output of:

```
{
  "jsonrpc": "2.0",
  "method": "getrawtransaction",
  "params": ["855bec3d4dcee690ff15b7d074e55ee2d59535756652b5f1c85594511b04f9f8", 1],
  "id": 1
}
```

and

```
{
   "jsonrpc": "2.0",
   "method": "getblockcount",
   "params":[],
   "id": 1
}
```

Since NEO/GAS is not NEP5 on 2.x, it's normal that `getnep5transfers` does not have any output (i think for `getapplicationlog` as well).

**Comment by shargon** [comment]
Old, if remains, please re-open
