### ISSUE TITLE
node: Fast synchronization failure

### ISSUE THREAD

**Issue by DingGeng-GitHub** [neo-project/neo-node#459]
已安装 ImportBlocks插件，并已下载全量离线包，并把chain.acc.zip放到和./neo-cli同级目录，但是在控制台show state发现block没变化，请问怎样使用离线包同步？

**Comment by superboyiii** [comment]
@DingGeng-GitHub 请问下你的neo-cli是什么版本？

**Comment by shargon** [comment]
Old, if remains, please re-open
