### ISSUE TITLE
node: Add more detail on neo-cli's runtime log

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-node#480]
I think neo-cli as a server, more detail should be added into runtime log to help developers analyzing issues. For example: Once neo-cli is killed by Linux, we aren't able to find any clue for locating the problem. Other example can be sync stagnate, if more logs could be output, it's really helpful for us.
And we could add an optional argument when start neo-cli to make log output active, such like: ./neo-cli -l.

**Comment by shargon** [comment]
Old, if remains, please re-open
