### ISSUE TITLE
node: neo-cli should load config.json from working directory, not binary directory

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-node#483]
neo-cli should be loading the config.json file from the current working folder, not the folder where the neo-cli binary is located. This would allow multiple nodes to run on a single machine (such as in a privatenet scenario) without needing multiple folders with neo-cli binaries.

If desired, we can fallback to the config.json from the binary folder if there is no config.json file in the current working folder.

**Comment by shargon** [comment]
Old, if remains, please re-open
