### ISSUE TITLE
node: no way to deploy contract w/o parameters via neo-cli

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-node#485]
neo-cli deploy command expects the second param to be a hex byte array describing the [parameter types](https://docs.neo.org/docs/en-us/sc/deploy/Parameter.html). However, there is no way to specify that a contract has no parameters. There should be a special token such as `<none>` that the caller can specify to indicate there are no parameters

**Comment by devhawk** [comment]
invoke also doesn't work correctly for scripts w/o input parameters

**Comment by lock9** [comment]
Hello @devhawk,  did you try using []? Did you try using 00 (void)?

**Comment by devhawk** [comment]
I reviewed the code. it simply calls HexToBytes, so [] wouldn't work. I could see using void as the special token (though void is FF not 00) but it would need to be handled special not just passed to HexToBytes as is done today

**Comment by shargon** [comment]
neo2 right?

**Comment by devhawk** [comment]
Yes neo 2

**Comment by tarikstafford** [comment]
Is there any plan to tackle this issue?

**Comment by hlogeon** [comment]
Are there any updates on this?

**Comment by Enqvida** [comment]
It's been almost a year... Chop chop :)

**Comment by Tommo-L** [comment]
We'll fix it recently, and also on Neo3.

**Comment by shargon** [comment]
Old, if remains, please re-open
