### ISSUE TITLE
Why we need two Dockerfile?

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-node#486]
Why we need two Dockerfile?

https://github.com/neo-project/neo-cli/blob/master/Dockerfile
https://github.com/neo-project/neo-cli/blob/master/ci/Dockerfile

Their content is also different. Is it possible to keep only one?

**Comment by vncoelho** [comment]
Yes, this is not a good practice.
Let's adjust one and make it the default.

The other one can be moved to a documentation if needed.

**Comment by shargon** [comment]
Agree, only one is better. But i can't see the second one now

**Comment by erikzhang** [comment]
I've removed the second one in #487.
