### ISSUE TITLE
node: Feature request: Ability to generate signed transactions offline

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-node#493]
It would be useful to be able to generate a signed transaction offline on an 'airgap' computer. This signed transaction can later be transferred to an online computer and broadcast on the blockchain. 

The idea of this feature is to prevent exposure of the private key to a computer that is connected to the internet and hence reduce the risk of the private key being intercepted by malicious parties. 

A comparable feature is offered for the Ethereum blockchain by MyEtherWallet.com

**Comment by shargon** [comment]
Duplicated with https://github.com/neo-project/neo-node/issues/227
