### ISSUE TITLE
node: hard to see blockchain loading progress

### ISSUE THREAD

**Issue by DavidGretzschel** [neo-project/neo-node#494]
It's really hard to see, how far the progress of downloading the blockchain is, because people aren't all that good at distinguishing 5, 6 or 7 digit numbers from each other, just at a glance.
Adding in a separator sign after every 3 or 4 digits would help to see this immediately.
Maybe add an option to switch between 3 and 4 digits to please Western and Chinese users, alike.

**Comment by shargon** [comment]
Old, if remains, please re-open
