### ISSUE TITLE
node: gui throws runtime failure 

### ISSUE THREAD

**Issue by anewio** [neo-project/neo-node#495]
After running about ~15 minutes, neo-gui throws an error seemly related to leveldb. Does anyone have any idea? 

NEO version: 2.9.6871
neo-gui: latest commit a6810512fc46dc42e99ea4d794e0eb3023a3240b
leveldb: latest commit a55f445b9cdbbefcdc823c52666efec0cca50ae2

Screenshot 
![capture](https://user-images.githubusercontent.com/1287541/47536155-8ccec580-d873-11e8-9ed0-cb47d0dc6723.JPG)

**Comment by shargon** [comment]
Old, if remains, please re-open
