### ISSUE TITLE
NEO3 neo-gui : which UI framework should we use?

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/neo-node#497]
Based on our discussion during the Community Assembly in Shanghai, we have reach the consensus about few things for neo-gui. And we also left some points to discuss further here on Github. 

**Things we have all agreed:**

- **Targeted Users**:  mainly developers & BlockChain purist 
- neo-gui need to be **cross-platform**
- neo-gui should have **all functions as neo-cli**, and being updated along with neo-cli
- UI/UX: maybe a little improvement
- **Tech Stack**: Cross Platform UI framework + .net Core 3.0
    *  `Avalonia` +  `.net Core 3.0`: NGD proposed it since it is close to WPF
    *  `Electron` +  `.net Core 3.0` :  most ppls' favorite during the NCA Discussion
    *  `ELF` + `.net Core 3.0`: NSPCC proposed this
    * Wait few months for MS official cross-platform UI framework: Shargon & Belane proposed

**The discussion was left are:**
- Which Cross Platform UI framework should we use ?
- Any more proposals or suggestions?

Thank you all for all the useful inputs and discussion. @devhawk @vncoelho @belane @shargon @lock9 @Lichen9618 @Ashuaidehao @lightszero. 

Let's discuss here for the remaining questions. Hopefully we can have a discussion soon so that we can move forward to develop gui for NEO3.

**Comment by wanglongfei88** [comment]
@neo-project/core @lightszero @lock9 can we close this issue now ? Since we have already agree on develop Neo-GUI with electron & .net.

**Comment by shargon** [comment]
It's good for me

**Comment by lightszero** [comment]
agree

**Comment by wanglongfei88** [comment]
Thanks for your feedback. 

I am closing this issue because it has been reach an agreement.
