### ISSUE TITLE
node: Wireframes for Neo Gui

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-node#498]
Hi,
We are planning to make a new Neo Gui, and for that, we need wireframes.
Usually, I have a list of features to build the wireframes on top of it, but if we build this internally, we may do this without that.
I think once we agree on the interface, we can move to the implementation. 

This can be started now, we don't have to wait for neo-project/neo-node#497

**Comment by shargon** [comment]
More elavorated in https://github.com/neo-project/neo-node/issues/500
