### ISSUE TITLE
Data convertor support

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/neo-node#499]
**Current situation**: 

we use a ByteArraya as return type for neo-gui, RPC request, neo-cli, etc. But ByteArray is not human readable. Users are always looking for a tool to be able to convert ByteArray to different data format, such as string, number, etc. For example:
 + ByteArray; `7472616e73666572`
 + String: `transfer`

**Proposal**

+ can we add data convertor support in neo-gui ?
+ such as :
    + ByteArray <-> String
    + ByteArray <-> Number
    + Address <-> ScriptHash (Big-endian/Little-endian)

**Comment by Tommo-L** [comment]
@wanglongfei88 see https://neo.org/converter/index
