### ISSUE TITLE
Backspace doesn't work when running neo-cli on linux

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-node#503]
Issue:
Backspace button doesn't work when running neo-cli on linux but it works well on win x64. It makes command line inputs will not be displayed but still have effect.
![image](https://user-images.githubusercontent.com/38493437/70413790-392d3480-1a93-11ea-936a-9fb622956309.png)
How to reproduce it:
Start node, input ```open wallet XX.json```, then input any command. This issue will appears.
Which version:
Latest master
Which device:
Linux
@neo-project/core

**Comment by erikzhang** [comment]
I don't have a linux environment here. Can anyone test it?

**Comment by shargon** [comment]
I will try it

**Comment by cloud8little** [comment]
@shargon  how did it work? I tried with the same result, and actually after any valid command(with valid result), all commands afterwards can not be shown on the screen, both linux and mac os.

**Comment by shargon** [comment]
It's working well in my laptop with the linux subshell (tested with master)

`Linux XXXX 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux`

Also in a debian (tested with 2x version)

`Linux XXXXX 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64`

**Comment by shargon** [comment]
Ups, my mistake, the problem is when open the wallet. Yes, it's happend to me. I will review it asap

**Comment by shargon** [comment]
I was able to find the bug, but not the solution

```
Console.ReadLine(); // Show the output
Console.Read();  // Read one char
Console.ReadLine(); // This doesn't show the output
```
![image](https://user-images.githubusercontent.com/3167973/70645427-42f69980-1c45-11ea-9a9d-daa8226277e4.png)

Console.Read disable the future outputs of ReadLine in Linux :S

**Comment by shargon** [comment]
The only solution I see is always read and write us.

**Comment by shargon** [comment]
Please, check this solution https://github.com/neo-project/neo-node/pull/516
