### ISSUE TITLE
[NEO3-neo-cli] latest neo-cli needs to be compatible with neo for rpcserver change

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-node#504]
Due to rpcserver change: https://github.com/neo-project/neo/pull/1340, latest neo-cli(https://github.com/neo-project/neo-node/pull/502) is incompatible with neo(#1340)
neo-cli needs to update to be consistent with neo.
![4591575887470_ pic_hd](https://user-images.githubusercontent.com/34291844/70429429-75708d00-1ab3-11ea-829f-f3f0ab0d5ef4.jpg)

**Comment by erikzhang** [comment]
Updated.
