### ISSUE TITLE
node: NEO3 neo-cli: Enable ctrl+w on linux

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-node#519]
How to reproduce it:
Start node, input any invalid command: open wallteccxxx, then enter ctrl+w to delete wallteccxxx , nothing happened.
Expected behavior: ctrl+w should delete word to correct typo error very fast.
Which version:
Latest master
Which device: Linux

**Comment by shargon** [comment]
Before open the wallet you can use it?

**Comment by cloud8little** [comment]
> Before open the wallet you can use it?

No, I mean preview1 I can use ctrl+w, but not sure after which commit of neo; when backspace did not work and command line disappear, then ctrl+w did not work.

**Comment by erikzhang** [comment]
So what's the point of adding "open wallet XX.json" to the reproduction steps?

**Comment by shargon** [comment]
Old, if remains, please re-open
