### ISSUE TITLE
node: Neo-gui(master-3.x)  breaks when making bulk operation.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-node#520]
I tried it on neo-gui just now, import 100 privkeys and export 130000+ blocks.
And I find an issue: When making exprt blocks or import key, if the number of data is a little big (For example: 100 WIFs for import key), a conflict will exist in Application.ThreadContext.RunMessageLoop which makes illegal value. But I think it's an issue from neo-gui itself since gui has too many functions incompatible on neo3.

**Describe the bug**
Neo-gui (console window) breaks when importing big number of privkeys.

**To Reproduce**
1. Open neo-gui, click Help -> Console.
2. Create a wallet and create 100 address.
3. Export keys to key.txt
4. Create another wallet and input `import key key.txt`.
5. Wait for a while and the bug apprears.

**Expected behavior**
Neo-gui breaks. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38493437/71070245-58c00d80-21b5-11ea-92e0-d232db114b25.png)
![image](https://user-images.githubusercontent.com/38493437/71070261-5f4e8500-21b5-11ea-9336-47526bf95522.png)
![image](https://user-images.githubusercontent.com/38493437/71070274-64abcf80-21b5-11ea-876f-5377099ebef6.png)

**Platform:**
 - OS: Windows 10 x64
 - Version neo-gui (latest master)

**Comment by shargon** [comment]
Old, if remains, please re-open
