### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by volekerb** [neo-project/neo-node#522]
Here are several links from the main page which don't work:

> Bootstrapping the network.
> In order to synchronize the network faster, please check here.

here -- doesn't work

> Usage
> See documentation. E.g. try show state or create wallet wallet.json.

documentation -- doesn't work

> Download pre-compiled binaries
> See also official docs. Download and unzip latest release.

official docs -- doesn't work and latest release as well

**Comment by vncoelho** [comment]
Was this solved, @Tommo-L ?

**Comment by Tommo-L** [comment]
Yes, we can close this now.
