### ISSUE TITLE
Docker: can't build and start docker according to documentation

### ISSUE THREAD

**Issue by volekerb** [neo-project/neo-node#524]
According to this:
https://github.com/neo-project/neo-node#build-into-docker

There is a way of build docker image from `neo-cli` directory.
```
cd neo-cli
docker build -t neo-cli .
```
This won't work since neo-cli doesn't contain Dockerfile.

But I was able to build docker image from the root repo. And 
`docker run -p 10332:10332 -p 10333:10333 --name=neo-cli-mainnet neo-cli` shuts down immediately and doesn't have any logs.

**Comment by Tommo-L** [comment]
Thanks for your suggestion, we will fix it.
