### ISSUE TITLE
Neo3: Shall we reload wallet before writing data to the wallet file?

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-node#533]
**Describe the bug**
Now in neo3, creating new address is both supported on neo-cli and rpc. So if we open the same wallet on neo-cli and rpc, then create new address respectively, the previous one will be overwritten.

**To Reproduce**
1.Open wallet 4.json on neo-cli.
![image](https://user-images.githubusercontent.com/43694095/71975750-b80ebc00-324f-11ea-8909-6fef35272e69.png)

2.Open wallet 4.json through rpc.
![image](https://user-images.githubusercontent.com/43694095/71975767-c361e780-324f-11ea-91fb-ebce00138f7d.png)

3.Create new address on neo-cli.
![image](https://user-images.githubusercontent.com/43694095/71975804-d1b00380-324f-11ea-9fe0-8eb138c76a17.png)

the wallet file:
```
{"name":null,"version":"3.0","scrypt":{"n":16384,"r":8,"p":8},"accounts":[{"address":"NTQr8tSEZtCGUwZriih8zNENqrPWA9QL4H","label":null,"isDefault":false,"lock":false,"key":"6PYWTF81zehptQWKjWhL41CYheWpeNBqDRNokHAef8eBcrxVfvChXb66au","contract":{"script":"DCECl36fZWA\u002BhdwJJrfV1CIGPAeBpAD0p2o3gH/bWg/nA/QLQQqQatQ=","parameters":[{"name":"signature","type":"Signature"}],"deployed":false},"extra":null},{"address":"Ncg7hG4sPA4AwCaubtGALNiy9SLnLFRrr1","label":null,"isDefault":false,"lock":false,"key":"6PYLoXvseQz33dhcCEmZMk5jMMrM67cc4APLyySzgY4MKVURaNvoRUY1JS","contract":{"script":"DCECe6fwSPvwBW2DQLEsdVqxN12VzOZZDNSyik5TZgEq\u002BJQLQQqQatQ=","parameters":[{"name":"signature","type":"Signature"}],"deployed":false},"extra":null}],"extra":null}
```

4.Create new address through rpc.
![image](https://user-images.githubusercontent.com/43694095/71975832-e7bdc400-324f-11ea-8b18-4f29cfa4b853.png)

then list address:
![image](https://user-images.githubusercontent.com/43694095/71975860-fb692a80-324f-11ea-9f6f-b2c3c05da67f.png)

we can see the wallet file is overwritten, the address Ncg7hG4sPA4AwCaubtGALNiy9SLnLFRrr1 has gone:
```
{"name":null,"version":"3.0","scrypt":{"n":16384,"r":8,"p":8},"accounts":[{"address":"NTQr8tSEZtCGUwZriih8zNENqrPWA9QL4H","label":null,"isDefault":false,"lock":false,"key":"6PYWTF81zehptQWKjWhL41CYheWpeNBqDRNokHAef8eBcrxVfvChXb66au","contract":{"script":"DCECl36fZWA\u002BhdwJJrfV1CIGPAeBpAD0p2o3gH/bWg/nA/QLQQqQatQ=","parameters":[{"name":"signature","type":"Signature"}],"deployed":false},"extra":null},{"address":"NP6TGVkuYx3mxYcmsKMT4vkES4PyYHDPjX","label":null,"isDefault":false,"lock":false,"key":"6PYQRpTBrhzotymgjVFHno4Cd6UiLaxqFgLBkVS6vz7pVe3rJie1qWknp9","contract":{"script":"DCECLcD02JY5NqUfiZkLtEwBZLUiWscF1dIQrdQu3ig93UELQQqQatQ=","parameters":[{"name":"signature","type":"Signature"}],"deployed":false},"extra":null}],"extra":null}
```

5.Reopen wallet 4.json on neo-cli, the address Ncg7hG4sPA4AwCaubtGALNiy9SLnLFRrr1 has gone:
![image](https://user-images.githubusercontent.com/43694095/71976006-3d926c00-3250-11ea-9133-e0d040c4f441.png)

**Additional context**
I think we should reload wallet before writing data to the wallet file. Otherwise, some data may be lost.

**Comment by erikzhang** [comment]
I think users of neo-cli should know what they are doing.
