### ISSUE TITLE
Error while creating a wallet.

### ISSUE THREAD

**Issue by fredrickabhishek** [neo-project/neo-node#537]
I'm creating neo-local network by going through official documents. but ended up with this error while creating the wallet. 
$ dotnet neo-cli.dll
NEO-CLI Version: 3.0.0-preview1

neo> create wallet 1.json
password: error

Have tried with earlier Neo-cli version also but didn't work

**Comment by shargon** [comment]
Could you check if the file already exists?

**Comment by fredrickabhishek** [comment]
yes checked there are no wallets created.

**Comment by fredrickabhishek** [comment]
I think my issue is fixed. Instead of opening neo-cli through a command line interface tool i created the wallet directly through neo-cli.exe and it worked fine.
