### ISSUE TITLE
Record contract id into abi and manifest files.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-node#540]
Now contract id is used to be storage key for smart contract. However if someone wants to get storage content, he has to invoke RPC method [getcontractstate] to get id. This is very inconvenient for developers to test contracts. My advice is to write id as a parameter into abi and manifest files whenever it's successfully deployed. This is much more conveninet.

**Comment by shargon** [comment]
It's required only if we want to know it inside the smart contract

**Comment by Tommo-L** [comment]
> It's required only if we want to know it inside the smart contract


Agree, we can convert from `scripthash` to `id` in RPC method.

```csharp
        private JObject GetStorage(JArray _params)
        {
            UInt160 script_hash = UInt160.Parse(_params[0].AsString());
            Int id = GetContractIdByScriptHash(script_hash); // <----   add this line
            byte[] key = _params[1].AsString().HexToBytes();
            StorageItem item = Blockchain.Singleton.View.Storages.TryGet(new StorageKey
            {
                Id = id,
                Key = key
            }) ?? new StorageItem();
            return item.Value?.ToHexString();
         }
```

**Comment by superboyiii** [comment]
@shargon One example:
I'm a nep5 owner. I have some coin A. One day I want to make transaction on cli. I remember my asset_id was A_xxxx, then I found the old contract was updated and destroyed. Then I ask many people. Some one told me the new asset_id is B_xxxx. Then I make transaction again. I finally find I don't have B on my address. And I ask NGD for help. Finally I found the new asset_id for updated A is C_xxxx. However, if I record the id of coin A's sc at first, I will always know which is my asset. Whatever how many times you update nep5 sc, id is always the **unique symbol** for contract to help people find where it is.

**Comment by shargon** [comment]
We can add a new RPC command for get this information

**Comment by superboyiii** [comment]
getcontractstate can do this.

**Comment by superboyiii** [comment]
getcontractstate can do this.

**Comment by shargon** [comment]
> getcontractstate can do this.

Then we don't need to change the core, right?

**Comment by superboyiii** [comment]
I just worry about if a contract was updated and the id  was not recorded, how to find the new one.

**Comment by doubiliu** [comment]
I think @Tommo-L 's code is enough, it has no impact on the user's use, just adjust the implementation logic of RPC

**Comment by superboyiii** [comment]
OK, I'll close this.
