### ISSUE TITLE
node: Invoke Neo Contract with PubKey as parameter fault

### ISSUE THREAD

**Issue by IsaAliev** [neo-project/neo-node#553]
I am trying to invoke neo smart contract code with neo-cli. There is CheckWitness call in the code I want to execute. And when I invoke the code I get Engine Faulted. I suppose there is a problem in pub key parameter format. Here is my contract code (simplified):

I do it on local blockchain of multiple nodes. Neo software is pulled from master-2.x.

```
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Services.Neo;

namespace Neo.SmartContract
{
    public class Class1 : Framework.SmartContract
    {
        public static object Main(string operation, byte[] caller)
        { 
            if (Runtime.CheckWitness(caller)) {
                return 10;
            } else
            {
                return 150;
            }
        }
    }
}
```

Here is what I call in cli:

```
invoke 7b5cd2ad18ef0be9d23e0e032d2aa58deb4ec6e0 some 027b30333e0d0e6552ae6d1da9f9409f551e35ee9719305e945dc4dcba998456ca
```

Here is what I get:

```
VM State: FAULT
Gas Consumed: 0,225
Evaluation Stack: []

Engine faulted.
```

**Comment by IsaAliev** [comment]
I have tried example code of Domain contract. Here is "register" method edited:

```
private static string Register(string domain, byte[] owner)
{
                if (!Runtime.CheckWitness(owner)) return $"check witness failed {owner.AsString()}";
                byte[] value = Storage.Get(Storage.CurrentContext, domain);
                if (value != null) return "value is not null";
                Storage.Put(Storage.CurrentContext, domain, owner);
                return "success";
}
```

I edited source code of neo-cli to parse params prefixed with "0x" as byte array. Now there is no fault when I make:

```
invoke 0x142764f67d5d64924f7120aa5339d94c15007a32 register some 0x030e87a0c5e652a44b51c2152779339246dc999c07da5e5f89771c44645ac71329
```

But I always get "check witness failed". I have tried several wallets and their pubKeys, also tried to pass script hash made as it described here https://docs.neo.org/developerguide/en/articles/wallets.html
However I have never passed witness check.

**Comment by denissuslov** [comment]
@IsaAliev Hi Isa, would you be interested in talking to Neo's Ecosystem Growth department about adding your wallet to our ecosystem? Feel free to add me on Discord Denis Suslov#6976 or by email: denissuslov@ngd.neo.org

**Comment by Tommo-L** [comment]
@IsaAliev  Neo-cli 2.x dose not support checkwitness, you'd better use RPC to invoke the contract https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/invokefunction.html  `The last one parameter is the address, which need to be `CheckWitness`.

The latest neo3-cli, and rpc already both have this function.  https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/invokefunction.html

**Comment by shargon** [comment]
Old, if remains, please re-open
