### ISSUE TITLE
Cannot call plugin commands

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-node#556]
I failed to call the plugin commands when testing https://github.com/neo-project/neo-modules/pull/188. 
Then I found that, now in neo-cli, it try to register plugin commands before the plugins are loaded, so none of them could be registered.
![image](https://user-images.githubusercontent.com/43694095/78109091-27e5aa80-742b-11ea-92a0-2d20e4d6844a.png)
@shargon Could you help fix it?

**Comment by shargon** [comment]
I will fix it
