### ISSUE TITLE
Adjust protocol.json fields

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-node#591]
As neo-core https://github.com/neo-project/neo/commit/9cbc025450f4120f795e6671da2683bfba6908b8 changed, we have to 
1. Rename `ValidatorsCount` to `MaxValidatorsCount`, default is 7.
2. Add a new `MaxCommitteeMembersCount` field, default is 21.

**Comment by vncoelho** [comment]
Very good.
