### ISSUE TITLE
Problem to run private (local) node

### ISSUE THREAD

**Issue by MatthewShelby** [neo-project/neo-node#592]
Based on this [instruction](https://neo-ngd.github.io/NEO-Tutorial/neo_docs_SmartContract_QuickStart/SmartContract_quickstart_en.html), I tried to implement a local blockchain. I did everything step by step. When I click on  "1Run.cmd" (which executes the command: >dotnet neo-cli.dll /rpc), I face with this Error:

Failed to load hostpolicy.dll

![2020-05-26 21_12_46-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/47936625/82934510-cd874700-9fa0-11ea-8676-d595817a85ef.png)

I use Win 8.1 - both .NetFramework and .Net Core SDK are Up to date.
If any other information I have to provide to help to solve this issue, plZ tell me.

**Comment by Tommo-L** [comment]
@MatthewShelby Which version do you use, neo-2.x or neo3-preview2?

**Comment by MatthewShelby** [comment]
The version I use:
[https://github.com/neo-project/neo-node/releases/tag/v3.0.0-preview2](url)
The instruction I use:
[https://neo-ngd.github.io/NEO-Tutorial/neo_docs_SmartContract_QuickStart/SmartContract_quickstart_en.html](url)

**Comment by Tommo-L** [comment]
@MatthewShelby 

https://neo-ngd.github.io/NEO-Tutorial/neo_docs_SmartContract_QuickStart/SmartContract_quickstart_en.html  It's only for neo2.x

If you want to setup v3.0.0-preivew2, plz refer to: 
1. Solo mode:  https://docs.neo.org/v3/docs/en-us/network/private-chain/solo.html 
2. Multiple nodes: https://docs.neo.org/v3/docs/en-us/network/private-chain/private-chain2.html

**Comment by Tommo-L** [comment]
@MatthewShelby I think this issue was fixed. I'll close it, and if you have any problem about it, you can reopen it. Thanks.

**Comment by MatthewShelby** [comment]
HI. sorry for the delay. it took a while for me to implement what you recommended.
What I did:
1. I got rid of all my old files. 
2. downloaded the [v3.preview2](https://github.com/neo-project/neo-node/releases/tag/v3.0.0-preview2).

3. made 4 copies as nodes.
4. used the neo-cli.exe in each node to create a wallet using "create wallet 1.json" 
![2020-05-29 16_38_39-NEO-CLI](https://user-images.githubusercontent.com/47936625/83258106-ee32e500-a1ca-11ea-8a85-949d209a8c20.png)

5. modified config.json like this:
![2020-05-29 16_40_39-config json - Notepad](https://user-images.githubusercontent.com/47936625/83258241-2afedc00-a1cb-11ea-85d0-6e707a006e27.png)

6. modified protocol.json like this:
![2020-05-29 16_41_22-ScreenShot](https://user-images.githubusercontent.com/47936625/83258307-436ef680-a1cb-11ea-901d-9452e832a8b4.png)

7. 1Run.cmd : 
![2020-05-29 16_42_37-Problem to run private (local) node · Issue #592 · neo-project_neo-node](https://user-images.githubusercontent.com/47936625/83258389-70bba480-a1cb-11ea-9d94-533f36e91c59.png)

Logn story short: I did everything step by step exactly as the instruction. also tested many other possibilities(like using GUI for creating wallets, ...)

8. Result:
![2020-05-29 16_56_15-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/47936625/83259471-55ea2f80-a1cd-11ea-802c-dc322473acd8.png)

 I'm about to pull my hair out. :((

**Comment by MatthewShelby** [comment]
I have no clue what this plugin is but, when I tried to install it manually, I faced this error:
![2020-05-29 19_41_42-Problem to run private (local) node · Issue #592 · neo-project_neo-node](https://user-images.githubusercontent.com/47936625/83275590-973a0980-a1e4-11ea-9a9b-3ecb4d6f0032.png)

**Comment by Tommo-L** [comment]
@MatthewShelby command is not complete, if you want to install a plugin, plz use `install [Plugin name]`. Here is the docs https://docs.neo.org/v3/docs/en-us/node/cli/cli.html#plugins

**Comment by Tommo-L** [comment]
I tried to setup multiple nodes, and it worked well. 
![image](https://user-images.githubusercontent.com/43396869/83371769-06d31300-a3f6-11ea-9afb-e153e66440bf.png)

Here is my four nodes' config.json. And `protocol.json` are the same. 
![image](https://user-images.githubusercontent.com/43396869/83372005-a690a100-a3f6-11ea-95df-daf09cdef429.png)

**Comment by MatthewShelby** [comment]
**Just for notice other users:**
### The problem has been solved just by moving all the files and operations into a Win 10 pc.
