### ISSUE TITLE
Update `plugins` command and add plugin description

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-node#597]
When users download neo-cli, they don't really know how many plug-ins we have and what they're for.

Update the `plugins` command as following:

```bash
> plugins
Installed plugins:
        LevelDBStore  Uses LevelDB to store the blockchain data
Uninstall plugins:
       RocksDBStore Uses RocksDBStore to store the blockchain data
       SystemLog   Prints the consensus log
       RpcServer     Enables RPC for the node
       ApplicationLogs  Synchronizes the smart contract log with the NativeContract log (Notify)
       RpcNep5Tracker  Enquiries NEP-5 balance and transactions history of accounts through RPC
       StatesDumper  Exports Neo-CLI status data
```

**Comment by joeqian10** [comment]
@erikzhang Can you add a virtual string `Description` in the abstract class `Plugin`? So I can override it in those plugins and add each description for each plugin.

**Comment by Tommo-L** [comment]
hard-code?  Even through we have `Description` field, how do you get the uninstalled plugins' description.

**Comment by shargon** [comment]
It could be done with attributes?

**Comment by joeqian10** [comment]
@Tommo-L Maybe hard-coded is a good idea for now. I can put plugin name and description in a dictionary.

**Comment by joeqian10** [comment]
```c#
        [ConsoleCommand("plugins", Category = "Plugin Commands")]
        private void OnPluginsCommand()
        {
            Dictionary<string, string> dic = new Dictionary<string, string>();
            dic.Add("ApplicationLogs", "Synchronizes the smart contract log with the NativeContract log (Notify)");
            dic.Add("LevelDBStore", "Uses LevelDB to store the blockchain data");
            dic.Add("RocksDBStore", "Uses RocksDBStore to store the blockchain data");
            dic.Add("RpcNep5Tracker", "Enquiries NEP-5 balance and transactions history of accounts through RPC");
            dic.Add("RpcServer", "Enables RPC for the node");
            dic.Add("StatesDumper", "Exports Neo-CLI status data");
            dic.Add("SystemLog", "Prints the consensus log");

            if (Plugin.Plugins.Count > 0)
            {
                Console.WriteLine("Installed plugins:");
                Plugin.Plugins.ForEach(p =>
                    {
                        var description = dic.GetValueOrDefault(p.Name, "Description");
                        Console.WriteLine("\t" + p.Name + "\t" + description);
                        dic.Remove(p.Name);
                    });
                Console.WriteLine("Uninstalled plugins:");
                dic.ForEach(p => Console.WriteLine("\t" + p.Key + "\t" + p.Value));
            }
            else
            {
                Console.WriteLine("No installed plugins");
            }
        }
```

**Comment by Tommo-L** [comment]
It's okay for me.

**Comment by joeqian10** [comment]
![image](https://user-images.githubusercontent.com/33386299/83472750-8e825580-a4ba-11ea-98f7-9a3085cc9a80.png)

**Comment by erikzhang** [comment]
Why we can list uninstalled plugins? I think the meaning of plugins is that anyone can write plugins, so their number should be unlimited, right?

**Comment by joeqian10** [comment]
@erikzhang Shall we provide a list of "official" plugins for now? Since these are frequently used, and developers can also use their own plugins which will not be listed.

**Comment by Tommo-L** [comment]
>  I think the meaning of plugins is that anyone can write plugins

That's right, then we need `Description` field in the abstract class `Plugin`?

> Why we can list uninstalled plugins?

It is mainly for the convenience of users. After downloading neo-cli, they can learn about the official plug-in functions when they enter `plugins` command. Otherwise, they need to go https://github.com/neo-project/neo-modules to learn about these.

**Comment by erikzhang** [comment]
I don't like this idea. But if other core developers like it, it's okay for me.

**Comment by Tommo-L** [comment]
@shargon @vncoelho what do you think?

**Comment by shargon** [comment]
I think that we should avoid hardcode this values, it's better to download it. Something like this...

We can download `plugins.json`, and this json can contain, the url for download the plugin and his description.

**Comment by Tommo-L** [comment]
Put `plugins.json` file in neo-modues?

**Comment by vncoelho** [comment]
Lets put these descriptions onchain...ahahah

I do not like this idea of hardcoding descriptions so much as well, as @erikzhang mentioned about having more plugins. 
@shargon direction looks good.
