### ISSUE TITLE
node: Neo-Cli Problem to install RpcServer Plugin

### ISSUE THREAD

**Issue by MatthewShelby** [neo-project/neo-node#603]
I want to install RpcServer. I used this command:

![1399-03-18 17_36_44-BookStore - Microsoft Visual Studio](https://user-images.githubusercontent.com/47936625/83969641-57f77100-a8e6-11ea-8c41-ada8108af319.png)

It looks like installation has been done, successfully, and without error. 
at the plugins folder in the neo-cli path (RpcServer.dll has been generated):

![1399-03-18 17_45_02-](https://user-images.githubusercontent.com/47936625/83969709-b58bbd80-a8e6-11ea-91ef-7676d3e88b88.png)

unfortunately, when I restat=rt neo-cli.exe this error occurs:

![1399-03-18 17_37_03-BookStore - Microsoft Visual Studio](https://user-images.githubusercontent.com/47936625/83969733-d3f1b900-a8e6-11ea-8d62-6d13ab3bf225.png)

I Tried both:

![1399-03-18 17_47_26-Release v3 0 0-preview2 · neo-project_neo-node](https://user-images.githubusercontent.com/47936625/83969764-013e6700-a8e7-11ea-9ea8-d5d706679a70.png)

from [here ](https://github.com/neo-project/neo-node/releases/tag/v3.0.0-preview2)but still not working.

can anybody help me?

**Comment by ProDog** [comment]
RpcServer need Microsoft.AspNetCore.ResponseCompression.dll, you can download it at https://github.com/ProDog/NEO-Test for a while, and put it in your neo-cli path.

**Comment by ProDog** [comment]
Can we add the `Microsoft.AspNetCore.ResponseCompression.dll` as a reference to neo-cli? @erikzhang @shargon @Tommo-L

**Comment by shargon** [comment]
neo-plugins should have dependencies

**Comment by ProDog** [comment]
RpcServer can't generate the `Microsoft.AspNetCore.ResponseCompression.dll`, so all users will encounter this problem if they compile the RpcServer by themselves.

**Comment by shargon** [comment]
It must be included in the zip and copied in the installation.

**Comment by Tommo-L** [comment]
> Can we add the `Microsoft.AspNetCore.ResponseCompression.dll` as a reference to neo-cli? @erikzhang @shargon @Tommo-L

For me, I think it's better to add them(only offical plugins' dependencies)  in neo-core.  It's convenient for users to use plugins, and it's easy for us to release plugins.

**Comment by superboyiii** [comment]
> I want to install RpcServer. I used this command:
> 
> ![1399-03-18 17_36_44-BookStore - Microsoft Visual Studio](https://user-images.githubusercontent.com/47936625/83969641-57f77100-a8e6-11ea-8c41-ada8108af319.png)
> 
> It looks like installation has been done, successfully, and without error.
> at the plugins folder in the neo-cli path (RpcServer.dll has been generated):
> 
> ![1399-03-18 17_45_02-](https://user-images.githubusercontent.com/47936625/83969709-b58bbd80-a8e6-11ea-91ef-7676d3e88b88.png)
> 
> unfortunately, when I restat=rt neo-cli.exe this error occurs:
> 
> ![1399-03-18 17_37_03-BookStore - Microsoft Visual Studio](https://user-images.githubusercontent.com/47936625/83969733-d3f1b900-a8e6-11ea-8d62-6d13ab3bf225.png)
> 
> I Tried both:
> 
> ![1399-03-18 17_47_26-Release v3 0 0-preview2 · neo-project_neo-node](https://user-images.githubusercontent.com/47936625/83969764-013e6700-a8e7-11ea-9ea8-d5d706679a70.png)
> 
> from [here ](https://github.com/neo-project/neo-node/releases/tag/v3.0.0-preview2)but still not working.
> 
> can anybody help me?

Could you retry it? It should be fixed after `Microsoft.AspNetCore.ResponseCompression.dll` be added to the ZIP after I re-release

**Comment by shargon** [comment]
Old, if remains, please re-open
