### ISSUE TITLE
About test Neo and Gas.

### ISSUE THREAD

**Issue by lambda2003** [neo-project/neo-node#605]
I just connected to testnet and try to get neo and gas for testing.
Where I can get it??

I just connect to https://neoscan-testnet.io/

config.json
{
  "ApplicationConfiguration": {
    "Paths": {
      "Chain": "Chain_{0}",
      "Index": "Index_{0}"
    },
    "P2P": {
      "Port": 20333,
      "WsPort": 20334
    },
    "RPC": {
      "BindAddress": "127.0.0.1",
      "Port": 20332,
      "SslCert": "",
      "SslCertPassword": ""
    },
    "UnlockWallet": {
      "Path":  "xxx",
      "Password": "xxx",
      "StartConsensus": false,
      "IsActive": true
    },
    "PluginURL": "https://github.com/neo-project/neo-plugins/releases/download/v{1}/{0}.zip"
  }
}

my protocol.json
{
  "ProtocolConfiguration": {
    "Magic": 1953787457,
    "AddressVersion": 23,
    "SecondsPerBlock": 15,
    "LowPriorityThreshold": 0.001,
    "StateRootEnableIndex": 4380000,
    "StandbyValidators": [
      "0327da12b5c40200e9f65569476bbff2218da4f32548ff43b6387ec1416a231ee8",
      "026ce35b29147ad09e4afe4ec4a7319095f08198fa8babbe3c56e970b143528d22",
      "0209e7fd41dfb5c2f8dc72eb30358ac100ea8c72da18847befe06eade68cebfcb9",
      "039dafd8571a641058ccc832c5e2111ea39b09c0bde36050914384f7a48bce9bf9",
      "038dddc06ce687677a53d54f096d2591ba2302068cf123c1f2d75c2dddc5425579",
      "02d02b1873a0863cd042cc717da31cea0d7cf9db32b74d4c72c01b0011503e2e22",
      "034ff5ceeac41acf22cd5ed2da17a6df4dd8358fcb2bfb1a43208ad0feaab2746b"
    ],
    "SeedList": [
      "seed1.ngd.network:20333",
      "seed2.ngd.network:20333",
      "seed3.ngd.network:20333",
      "seed4.ngd.network:20333",
      "seed5.ngd.network:20333",
      "seed6.ngd.network:20333",
      "seed7.ngd.network:20333",
      "seed8.ngd.network:20333",
      "seed9.ngd.network:20333",
      "seed10.ngd.network:20333"
    ],
    "SystemFee": {
      "EnrollmentTransaction": 10,
      "IssueTransaction": 5,
      "PublishTransaction": 5,
      "RegisterTransaction": 100
    }
  }
}

Any suggestion or help??
Thank you.

**Comment by ProDog** [comment]
https://neowish.ngd.network/  or  https://neo.org/testcoin/apply

**Comment by dns7030** [comment]
@lambda2003 Also I can send you some testnet Neo and Gas directly, please add me on Discord: Denis Suslov#6976

**Comment by lambda2003** [comment]
@ProDog Thank you. - It took a long(3 business days??) to get test coin after submitting an application to https://neo.org/testcoin/apply. :(

@dns7030 Thank you for your kindness. :)

**Comment by dns7030** [comment]
@lambda2003 No problem, what's your handle on Discord? Would be great to chat.

**Comment by dns7030** [comment]
Are you developing something on Neo? @lambda2003  I work for Neo Ecosystem Growth, would love to talk about how we can promote your project.
