### ISSUE TITLE
Bug of invoke smart contract

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-node#609]
It prompts the note `insufficient balance` when I call a method that does not exist in the contract.

![image](https://user-images.githubusercontent.com/6295602/84994342-218ae300-b17d-11ea-83e8-d9b0af2c2da5.png)

**Comment by shargon** [comment]
It will be solved soon, with https://github.com/neo-project/neo-vm/pull/333

**Comment by superboyiii** [comment]
@shargon neo and neo-vm is ready, but we need to adjust in neo-node as well.
