### ISSUE TITLE
neo-cli needs way to send string messages to plugins

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-node#620]
There needs to be a way for neo-cli users to send string messages to plugins via Plugin.SendMessage static method

**Comment by shargon** [comment]
With console commands they can, any use case?

**Comment by devhawk** [comment]
Example: Send a command to the RpcServer to start/stop/ w/o needing to shutdown the node or uninstall the plugin

Maybe something like 

``` shell
neo-cli> plugin message rpcserver shutdown
```

everything after "plugin message" would be sent via Plugin.SendMessage.

**Comment by erikzhang** [comment]
Plugins can register commands to the cli.

**Comment by shargon** [comment]
I think that rpcserver should expose a command cli, rpc shudtown, rpc start... it's the easier way to comunicate with the user.

**Comment by devhawk** [comment]
> Plugins can register commands to the cli.

If there's an existing way to do this, that's great. Is there an example demonstrating this somewhere?

**Comment by shargon** [comment]
https://github.com/neo-project/neo-modules/blob/40f9180d2b3e4e038d77ec8da9af27ec2ac34197/src/StatesDumper/StatesDumper.cs#L44

**Comment by devhawk** [comment]
Thanks @shargon. No need for this feature then.
