### ISSUE TITLE
Similar Piece of Code for Invoke and SendTransaction Function

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-node#632]
There is two piece of code, very much similar in the function body. can we integrate them? because in the period of updating code, there may be inconsistency, for example, the 1 shows "Result Stack", 2 shows "Evaluation Stack". It will cause some confusion.
besides, the part using (ApplicationEngine engine = ApplicationEngine.Run(tx.Script, tx, null, testMode: true))  is almost the same.

1. 

https://github.com/neo-project/neo-node/blob/dec52fbd25850113f5372bf8d2aa7c97a6ffcced/neo-cli/CLI/MainService.cs#L545-L569

2. 

https://github.com/neo-project/neo-node/blob/dec52fbd25850113f5372bf8d2aa7c97a6ffcced/neo-cli/CLI/MainService.cs#L490-L506

**Comment by shargon** [comment]
I will unify it
