### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by zgmqdl** [neo-project/neo-node#648]
启动报错
neo> Unhandled exception. System.TypeLoadException: Could not load type 'Neo.Plugins.IRpcPlugin' from assembly 'Neo, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by ProDog** [comment]
What version and plugins are you using?

**Comment by ProDog** [comment]
@zgmqdl Have you solved your problem?
