### ISSUE TITLE
node: Multiple contract deployment error

### ISSUE THREAD

**Issue by ryanfalzon** [neo-project/neo-node#652]
Receiving the following error in the node-cli after I deploy 3 smart contracts:
```console
Error: Operation is not valid due to the current state of the object.
```
This forces me to delete the node-cli folder and start from scratch!

**Comment by ProDog** [comment]
Can you reproduce it or provide more information? I have no problem when deploying 3 contracts.

**Comment by shargon** [comment]
Old, if remains, please re-open
