### ISSUE TITLE
neo-gui master branch doesn't compile against neo master branch

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-node#653]
`InvokeContractDialog.button5_Click` is calling `ApplicationEngine.Run(tx_test.Script, tx_test, testMode: true);`. 

testMode parameter has been removed from ApplicationEngine

**Comment by superboyiii** [comment]
> `InvokeContractDialog.button5_Click` is calling `ApplicationEngine.Run(tx_test.Script, tx_test, testMode: true);`.
> 
> testMode parameter has been removed from ApplicationEngine

It's no longer be maintained. We've already working on an absolutely new neo-gui (https://github.com/neo-ngd/Neo3-GUI)

**Comment by erikzhang** [comment]
I think it has been fixed by #654.
