### ISSUE TITLE
neo-cli preview3.0 Unable to start

### ISSUE THREAD

**Issue by hzccc** [neo-project/neo-node#657]
dotnet version : 3.1.401
```
  neo> System.Collections.Generic.KeyNotFoundException: The given key 'LevelDBStore' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Neo.NeoSystem..ctor(String storageEngine)
   at Neo.CLI.MainService.Start(String[] args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libunwind-dev' instead of 'libunwind8-dev'
libleveldb-dev is already the newest version (1.20-2).
libunwind-dev is already the newest version (1.2.1-8).
libsqlite3-dev is already the newest version (3.22.0-1ubuntu0.4).
sqlite3 is already the newest version (3.22.0-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
```

**Comment by Qiao-Jin** [comment]
You should add a libleveldb.dll into root directory;

**Comment by hzccc** [comment]
> You should have a `LevelDBStore` plugin in `Plugin` folder

Yes I have

**Comment by hzccc** [comment]
![image](https://user-images.githubusercontent.com/20179548/91812408-a5744780-ec63-11ea-9287-2ccc711177cb.png)

**Comment by hzccc** [comment]
neo-cli v 2.11.0.0  Run normally on this machine

**Comment by hzccc** [comment]
Nearly forgot，My System is Ubuntu 18.04

**Comment by cloud8little** [comment]
> Nearly forgot，My System is Ubuntu 18.04

did you try to re-install the LevelDBStore plugin?

**Comment by hzccc** [comment]
> > Nearly forgot，My System is Ubuntu 18.04
> 
> did you try to re-install the LevelDBStore plugin?

Yes，I've deleted and downloaded it several times

**Comment by shargon** [comment]
Are you using the data folder from a different version?

**Comment by hzccc** [comment]
> Are you using the data folder from a different version?
Maybe my system is also running a different version of neo-cli?  but neo-cli v2.11 does not set the data folder

**Comment by hzccc** [comment]
> Are you using the data folder from a different version?

Maybe my system is also running a different version of neo-cli? but neo-cli v2.11 does not set the data folder

**Comment by hzccc** [comment]
> Are you using the data folder from a different version?

I chose RocksDBStore and it won't work
