### ISSUE TITLE
How do I start RPC? The RPCServer plug-in has been installed

### ISSUE THREAD

**Issue by hzccc** [neo-project/neo-node#658]
version neo-cli 3.0 preview3

**Comment by superboyiii** [comment]
> version neo-cli 3.0 preview3

Whenever you restart neo-cli after the PRCServer plugin is installed.

**Comment by hzccc** [comment]
> > version neo-cli 3.0 preview3
> 
> Whenever you restart neo-cli after the PRCServer plugin is installed.

啊 上海的呀 那说中文了。有没有参考的rpc配置文件？确实已经启动rpcserver了 但是监听的端口是10332，这是为什么呢？我启用的配置是testnet的

**Comment by superboyiii** [comment]
> > > version neo-cli 3.0 preview3
> > 
> > 
> > Whenever you restart neo-cli after the PRCServer plugin is installed.
> 
> 啊 上海的呀 那说中文了。有没有参考的rpc配置文件？确实已经启动rpcserver了 但是监听的端口是10332，这是为什么呢？我启用的配置是testnet的

./neo-cli/Plugins/RpcServer/config.json 修改端口

**Comment by hzccc** [comment]
> > > > version neo-cli 3.0 preview3
> > > 
> > > 
> > > Whenever you restart neo-cli after the PRCServer plugin is installed.
> > 
> > 
> > 啊 上海的呀 那说中文了。有没有参考的rpc配置文件？确实已经启动rpcserver了 但是监听的端口是10332，这是为什么呢？我启用的配置是testnet的
> 
> ./neo-cli/Plugins/RpcServer/config.json 修改端口

谢谢 🙏

**Comment by Tommo-L** [comment]
@hzccc  we'll close this issue, I think it's fixed. If you still have any problem, you can reopen this issue or open a new issue.
