### ISSUE TITLE
Node >= 2.11.0 crashes after some time

### ISSUE THREAD

**Issue by merl111** [neo-project/neo-node#666]
Nodes with version >= 2.11.0 are crashing with:

`neo-cli: /build/leveldb-zdGJo2/leveldb-1.22/db/dbformat.cc:15: uint64_t leveldb::PackSequenceAndType(uint64_t, leveldb::ValueType): Assertion seq <= kMaxSequenceNumber failed.
Aborted`

Happens every few hours, so it's not a one-timer.

Setup:
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

LevelDB:
/usr/lib/x86_64-linux-gnu/libleveldb.so.1.22.0

The node was resynced from genesis, the problem doesn't seem to happen during sync from file, but only during network sync.

Let me know if you need any other information from me to debug the issue.

**Comment by senzsze** [comment]
Issue persisting for me while synchronizing after upgrading to Neo-CLI v2.12, need s ript to auto restart to avoid having to monitor frequently

**Comment by EdgeDLT** [comment]
Noticed the same with v2.12. Set up a daemon to take care of it but there does seem to be some instability issues in this version.

**Comment by senzsze** [comment]
Has about a dozen crashes while syncing in the last 24-ish hours :)

**Comment by erikzhang** [comment]
It should be fixed by https://github.com/neo-project/neo/pull/1940

**Comment by merl111** [comment]
Testing right now, built from latest 2.x master branch, will update in a few hours.

**Comment by merl111** [comment]
Didn't fix it, crashed again.
