### ISSUE TITLE
neo-cli isn't able to show exception msg from Smart Contract but just show Error 

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-node#672]
When I try to go into this code via `invoke` in neo-cli
![image](https://user-images.githubusercontent.com/38493437/95834113-1f254800-0d6f-11eb-9b16-2de22bf9432e.png)
It returned `Error: An unhandled exception was thrown.`
![image](https://user-images.githubusercontent.com/38493437/95834969-3a448780-0d70-11eb-9f02-7ed7cfa38826.png)
![image](https://user-images.githubusercontent.com/38493437/95841268-bee6d400-0d77-11eb-9eaa-86a30ed1b5ed.png)
![image](https://user-images.githubusercontent.com/38493437/95844577-a678b880-0d7b-11eb-8a2d-432bd8393835.png)
Expect: `"No authorization."`
***By the way, `GetExceptionMessage` is executed twice. It also doesn't make sense.***

**Comment by shargon** [comment]
I think that the Exception inside the VM emit an event, not a real exception.

**Comment by Tommo-L** [comment]
VM shouldn't emit an event, it should be completely decoupled from neo-core.

**Comment by superboyiii** [comment]
> I think that the Exception inside the VM emit an event, not a real exception.

I found it's a dependecy issue since neo's vm dependency is too old. When I upgrade to the one before last, it throwed exception successfully.
```
neo> invoke 0x254b9decd76080ef368e7a6b0a065938dfbc31cf destroy [] 0xf642a0401fdd56a03114639a98b7963eb587a30a 0x9f2dd7df630980dce111d3b31ebe35d3cfae58cd 0x9f2dd7df630980dce111d3b31ebe35d3cfae58cd
Invoking script with: 'EMAMB2Rlc3Ryb3kMFM8xvN84WQYKa3qONu+AYNfsnUslQWJ9W1I='
VM State: HALT
Gas Consumed: 0.0230232
Result Stack: [{"type":"Any"}]
Relay tx(no|yes): n
neo> invoke 0x254b9decd76080ef368e7a6b0a065938dfbc31cf destroy [] 0x9f2dd7df630980dce111d3b31ebe35d3cfae58cd 0x9f2dd7df630980dce111d3b31ebe35d3cfae58cd 0x9f2dd7df630980dce111d3b31ebe35d3cfae58cd
Invoking script with: 'EMAMB2Rlc3Ryb3kMFM8xvN84WQYKa3qONu+AYNfsnUslQWJ9W1I='
VM State: FAULT
Gas Consumed: 0.0132447
Result Stack: []
Error: An unhandled exception was thrown. No authorization.
Error: An unhandled exception was thrown. No authorization.
```

**Comment by ProDog** [comment]
Now neo-cli print the error message repeated, which is here:
https://github.com/neo-project/neo-node/blob/00946fdec9d47570fbdf06b4dc3bf521e91be391/neo-cli/CLI/MainService.Contracts.cs#L76

https://github.com/neo-project/neo-node/blob/00946fdec9d47570fbdf06b4dc3bf521e91be391/neo-cli/CLI/MainService.Contracts.cs#L85

Maybe we can use `e.Message` instead of `GetExceptionMessage(e)`  for  `MakeTransaction`, then will print this error:
https://github.com/neo-project/neo/blob/6886991ca67f2c2148429ba87bf7d782f8cb12c8/src/neo/Wallets/Wallet.cs#L353

**Comment by Tommo-L** [comment]
see https://github.com/neo-project/neo-node/pull/674
