### ISSUE TITLE
Failed to withdraw GAS, and the transfer also failed. The 3.0 master version is used

### ISSUE THREAD

**Issue by qcjxberin** [neo-project/neo-node#677]
![image](https://user-images.githubusercontent.com/5792218/97775967-bd067880-1b9f-11eb-936b-74e5419f939b.png)

Failed to withdraw GAS, and the transfer also failed. The 3.0 master version is used

**Comment by chenzhitong** [comment]
Now it work well, If there are still erros, please raise issues here https://github.com/neo-ngd/neo3-gui
