### ISSUE TITLE
Why is 2.12.2 storage much bigger than 2.10.3?

### ISSUE THREAD

**Issue by lcgogo** [neo-project/neo-node#678]
Because I see a issue that 2.10.3 cannot upgrade to 2.12.2 without resync, I start another 2.12.2 node.
After both catch up the latest height, the disk usage of 2.12.2 is much bigger than 2.10.3

2.12.2 use more than 100GB

du -h
105G	./Chain_00746E41
105G	.

2.10.3 use only 18GB

du -h
16K	./lost+found
18G	./Chain_00746E41
18G

**Comment by ProDog** [comment]
You can see change log of https://github.com/neo-project/neo-node/releases/tag/v2.10.3-neox-preview1.
the main reason is add `StateRoot`.

**Comment by lcgogo** [comment]
ack
