### ISSUE TITLE
node: neo-cli has a memory leak

### ISSUE THREAD

**Issue by jens-j** [neo-project/neo-node#696]
I recenty upgraded from version 2.10.0 to 2.12.1. I noticed that this new version of neo-cli slowly fills up my memory until it crashes.

**Comment by Qiao-Jin** [comment]
Could you provide the error log?

**Comment by jens-j** [comment]
Sure, I just have to wait for it to happen before I can post it,

**Comment by Tommo-L** [comment]
Hi @jens-j , plz use v12.2.2 https://github.com/neo-project/neo-node/releases/tag/v2.12.2, it's a stable version.

**Comment by txsdev** [comment]
Hi, could you resolved the problem?

**Comment by jens-j** [comment]
No I never did. Try the newest version. If the problem still exists, only the devs can solve it.

**Comment by shargon** [comment]
Old, if remains, please re-open
