### ISSUE TITLE
node: LevelDB error

### ISSUE THREAD

**Issue by asifshiraz** [neo-project/neo-node#703]
I am following all the steps for installing neo-cli locally.
1. Cloned the repo, with master branch.
2. Built using visual studio and published.
3. Switched names of protocol and config files. 
4. Copied two plugins in publish folder, RpcServer and LevelDbStore.

Then, when I run neo-cli, I get the following error:

![image](https://user-images.githubusercontent.com/7054246/102938132-4d12c100-4471-11eb-8ea8-86851b67009c.png)

**Comment by superboyiii** [comment]
> I am following all the steps for installing neo-cli locally.
> 
> 1. Cloned the repo, with master branch.
> 2. Built using visual studio and published.
> 3. Switched names of protocol and config files.
> 4. Copied two plugins in publish folder, RpcServer and LevelDbStore.
> 
> Then, when I run neo-cli, I get the following error:
> 
> ![image](https://user-images.githubusercontent.com/7054246/102938132-4d12c100-4471-11eb-8ea8-86851b67009c.png)

wait for https://github.com/neo-project/neo-modules/pull/442 and https://github.com/neo-project/neo/pull/2179

**Comment by chenzhitong** [comment]
Now it works well. Use master branch and try again? @asifshiraz

**Comment by shargon** [comment]
Old, if remains, please re-open
