### ISSUE TITLE
Deal with void return value correctly

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-node#710]
Now the evaluation stack return nothing when there is no return value. so it will caused error on this piece of code.

https://github.com/neo-project/neo-node/blob/3acb8aa42c42bc2817fd958444a7dab182c19082/neo-cli/CLI/MainService.cs#L565-L568

for example:

invoke NNS with AddRoot method:

```cs
        [ContractMethod(0_03000000, CallFlags.WriteStates)]
        private void AddRoot(ApplicationEngine engine, string root)
        {
            if (!rootRegex.IsMatch(root)) throw new ArgumentException(null, nameof(root));
            if (!CheckCommittee(engine)) throw new InvalidOperationException();
            StringList roots = engine.Snapshot.Storages.GetAndChange(CreateStorageKey(Prefix_Roots), () => new StorageItem(new StringList())).GetInteroperable<StringList>();
            int index = roots.BinarySearch(root);
            if (index >= 0) throw new InvalidOperationException("The name already exists.");
            roots.Insert(~index, root);
        }
```

![93b7aabe37bf9ab28ec003418232b28](https://user-images.githubusercontent.com/34291844/104262513-bca12c80-54c2-11eb-8e26-ae7df3cf512d.png)
![34c26ebf6d31486e2d6dbfac8b4789a](https://user-images.githubusercontent.com/34291844/104262517-be6af000-54c2-11eb-986e-f15e7efd59d7.png)
![c35923f27eae3d035b043bdc03886bf](https://user-images.githubusercontent.com/34291844/104262521-c034b380-54c2-11eb-80a3-eb7df94704ca.png)

**Comment by chenzhitong** [comment]
Work fine in mine
```c#
public class Contract1 : SmartContract
    {
        public static void a()
        {
            
        }
    }
```

![image](https://user-images.githubusercontent.com/6295602/104552805-7095e980-5674-11eb-9f51-610b56a132d6.png)
