### ISSUE TITLE
missing parameter error when using invoke <contract> transfer with neo3-preview4 

### ISSUE THREAD

**Issue by djm34** [neo-project/neo-node#728]
Hello, 

I created a NEP17 contract under neo3-preview4 (following) the example. 

The command transfer works. 
However using either neo-cli or curl, it constantly failed because of a 4th parameter which is missing (from, to, amount and something else missing). 
I tried every json combination, and I always end up with an error.

here an example: 

curl -H 'Content-Type: application/json' -v -d '{"jsonrpc":"2.0","method":"invokefunction","params":["0x1415cac91819029f329aec275c937c8158ee64b4","transfer",[{"type":"Hash160","value":"0x621c0c4e4b8df11c15bdb04f27b597a0cc7a047c"},{"type":"Hash160","value":"
0x8c5d07e39d3d5947c31da98b797c5f322e1bc9af"},{"type":"Integer","value":"100"}]],"id":1234}' localhost:13332

end I get this answer: 
{"jsonrpc":"2.0","id":1234,"result":{"script":"AGQMFK/JGy4yX3x5i6kdw0dZPZ3jB12MDBR8BHrMoJe1J0\u002BwvRUc8Y1LTgwcYhPADAh0cmFuc2ZlcgwUtGTuWIF8k1wn7JoynwIZGMnKFRRBYn1bUg==","state":"FAULT","gasconsumed":"0.0099942","exception":"Method transfer Expects 4 Arguments But Receives 3 Arguments","stack":[]}}

so the question what is that 4th parameter and how my json request including that parameter should be written

(or alternatively, I would suggest to add the "transfer <contract>" method to RpcServer)

**Comment by cloud8little** [comment]
you need to pass 4 parameters, the fourth param is object type, so you can just pass string, or other object-type.

curl -H 'Content-Type: application/json' -v -d '{"jsonrpc":"2.0","method":"invokefunction","params":["0x1415cac91819029f329aec275c937c8158ee64b4","transfer",[{"type":"Hash160","value":"0x621c0c4e4b8df11c15bdb04f27b597a0cc7a047c"},{"type":"Hash160","value":"
0x8c5d07e39d3d5947c31da98b797c5f322e1bc9af"},{"type":"Integer","value":"100"},{"type":"String","value":"random"}]],"id":1234}' localhost:13332

**Comment by djm34** [comment]
Hi,
thanks a lot, it worked (I tried that before but I might have had an error). 
However the problem is that the transfer doesn't not seem to happen. 

Here what I tried: 

curl -H 'Content-Type: application/json' -v -d '{"jsonrpc":"2.0","method":"invokefunction","params":["0x92049d6721839fbed9d6b770ed90d271afae9747","transfer",[{"type":"Hash160","value":"0x621c0c4e4b8df11c15bdb04f27b597a0cc7a047c"},{"type":"Hash160","value":"0xe9fb13f75c1e9d6365f90a22d4d24fb6275d4d15"},{"type":"Integer","value":"1000"},{"type":"String","value":"truc"}],[{"account":"0x621c0c4e4b8df11c15bdb04f27b597a0cc7a047c","scopes": "CalledByEntry","allowedcontracts":[],"allowedgroups":[]}]],"id":1234}' localhost:13332


and the answer: 

{"jsonrpc":"2.0","id":1234,"result":{"script":"DAR0cnVjAegDDBQVTV0ntk/S1CIK\u002BWVjnR5c9xP76QwUfAR6zKCXtSdPsL0VHPGNS04MHGIUwAwIdHJhbnNmZXIMFEeXrq9x0pDtcLfW2b6fgyFnnQSSQWJ9W1I=","state":"HALT","gasconsumed":"0.1148962","exception":null,"stack":[{"type":"Integer","value":"1"}],"tx":"ADDAxxtUUa8AAAAAAHbWEgAAAAAAXvkAAAF8BHrMoJe1J0\u002BwvRUc8Y1LTgwcYgEAXAwEdHJ1YwHoAwwUFU1dJ7ZP0tQiCvllY50eXPcT\u002B\u002BkMFHwEesygl7UnT7C9FRzxjUtODBxiFMAMCHRyYW5zZmVyDBRHl66vcdKQ7XC31tm\u002Bn4MhZ50EkkFifVtSAUIMQCVr4eTQNWhRERovoJf0rtYZXtrG7i0iEmIzncr8ZznUR00wiiuGXDGwTkILyO9VhmZaueDP\u002BkYcw1PeSH9dnIEpDCECzlsSgLaaFH0RaUxjeHjxsf67qBwQXcVgKfkKZorspOkLQZVEDXg="}}


But when checking the balance, the account didn't receive the tokens. 

Do I need something else to sign and relay the transaction ?
Thanks for your help.

**Comment by csmuller** [comment]
The `invokefunction` RPC method does not change the state of the blockchain. It only tests the transaction. The Neo docs say: "This method is used to test your VM script as if they ran on the blockchain at that point in time. This RPC call does not affect the blockchain in any way." (see [here](https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/invokefunction.html)).

To actually persist the change to the blockchain a transaction needs to be built and transmitted through the blockchain network.
(1) One way to do this is by using the neo-cli. You could use the `transfer` method for this, as you already now, i think.
For example: `transfer 0x4961bf0ab79370b23dc45cde29f568d0e0fa6e93 NZNos2WqTbu5oCgyfss9kUJgBXJqhuYAaj 100`, which transfers 100 NEO to the address `NZN...`  
(2) Another way is to use the `sendfrom` RPC method in case you have an open wallet on the neo-node. For example: 
```json 
{
  "jsonrpc": "2.0",
  "method": "sendfrom",
  "params": [
		"3e1c7c20b1ddbb998b1048061e7665c426b85b14", "NZNos2WqTbu5oCgyfss9kUJgBXJqhuYAaj", "NX8GreRFGFK5wpGMWetpX93HmtrezGogzk", 0.1
	],
  "id": 1
}
```
Where the first parameter is the contract hash, the second the source account, the third the receiving account, and the fourth the amount to transfer.

**Comment by djm34** [comment]
ok thanks a lot, I thought that sendfrom was only for neo/gas
actually (just found out) it is also possible to use invokefunction, then send the generated tx with sendrawtransaction. But sendfrom is definitely easier. 
Actually I am trying to find a way to automatize all smartcontract management.

**Comment by csmuller** [comment]
If you want to automate interaction with your smart contract and the Neo blockchain in general, you could use one of the many libraries that provide the required functionality for this, e.g., [neow3j](https://neow3j.io/) for Java, [neo-one](https://neo-one.io/) for TypeScript, [neo-go](https://github.com/nspcc-dev/neo-go) for Go.

**Comment by djm34** [comment]
neow3j would probably a good option, does it support neo3-preview4 ?

**Comment by csmuller** [comment]
Yes, from version 3.6.0 neow3j supports preview4. The latest version at this time is 3.6.1.
Next to the documentation at [neow3j.io](https://neow3j.io/) there is an [example repository](https://github.com/neow3j/neow3j-examples-java/tree/master/neo3-examples) that provides many example usages of the library.

Please don't hesitate to open [issues](https://github.com/neow3j/neow3j/issues) or [discussions](https://github.com/neow3j/neow3j/discussions) if you get stuck or find inconveniences in the library.

**Comment by cloud8little** [comment]
@djm34  so this is not an issue, can you close?
