### ISSUE TITLE
node: Private key format

### ISSUE THREAD

**Issue by therepo90** [neo-project/neo-node#744]
Hey im trying to get my head around https://docs.neo.org/developerguide/en/articles/wallets.html#1-private-key
Im trying to reproduce steps in example WIF and HEX data.
It says to create WIF we should prepend the hex data with 0x80, and suffice it with 0x01
so given input c7134d6fd8e73d819e82755c64c93788d8db0961929e025a53363c4cc02a6962
we get 80c7134d6fd8e73d819e82755c64c93788d8db0961929e025a53363c4cc02a696201
but now if we try to base58 it with https://www.appdevtools.com/base58-encoder-decoder
we get  3urGV9gv4F6QmMWbB4BUPC5jzgTbEX3EHNKSgZ1TBHDwpjr
which is not the example one L3tgppXLgdaeqSGSFw1Go3skBiy8vQAM7YMXvTHsKQtE16PBncSU

Also when decoding the WIF with the tool we get 80c7134d6fd8e73d819e82755c64c93788d8db0961929e025a53363c4cc02a696201cb370f59
which is not the input hex on the website.
Whats wrong?

This is important as im trying to figure out my mispelling characters in the private key where I have some neo on.

**Comment by shargon** [comment]
You need to add the checksum at the end `Base58CheckEncode` is not only a Base58, you can see the logic here:

https://github.com/neo-project/neo/blob/7b24f8efaf752e0eb64eaa258a0b29f6359194be/src/neo/Cryptography/Base58.cs#L26-L35

**Comment by shargon** [comment]
Old, if remains, please re-open
