### ISSUE TITLE
node: neo-gui master branch compilation errors 

### ISSUE THREAD

**Issue by anewio** [neo-project/neo-node#745]
Pull the latest from master branch (commit #740), neo-gui project has 20 compilation errors

![image](https://user-images.githubusercontent.com/1287541/107892232-9e22bc80-6ed8-11eb-9a51-8ffd33f4a736.png)

The first error is at line #20 of `BulkPayDialog.cs`. Do I missed anything? Please have a look. 

![image](https://user-images.githubusercontent.com/1287541/107892311-20ab7c00-6ed9-11eb-8c70-ab0a72b4cb7e.png)

**Comment by shargon** [comment]
Old, if remains, please re-open
