### ISSUE TITLE
Incorrect Folder Name for Logger

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-node#747]
![999a29275509e4a45aec5dcaa68b476](https://user-images.githubusercontent.com/34291844/108456611-a64d7400-72ab-11eb-8aa3-5b3a11e023b1.png)

https://github.com/neo-project/neo-node/blob/c784a6cb9e8787b2e58eedc16b49bdb029abe8fb/neo-cli/CLI/Logger.cs#L77-L93

**Comment by bettybao1209** [comment]
So should we just use the directory named `Log`？
