### ISSUE TITLE
node: Logs and Data_LevelDB folder should contain magic id

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-node#754]
neo-cli will deal with Logs and Data_LevelDB folder without the magic number, should they also be updated? @erikzhang

```cs
        public LoggerSettings(IConfigurationSection section)
        {
            this.Path = section.GetValue("Path", "Logs_{0}");
            this.ConsoleOutput = section.GetValue("ConsoleOutput", false);
            this.Active = section.GetValue("Active", false);
        }
```
```cs
        public StorageSettings(IConfigurationSection section)
        {
            this.Engine = section.GetValue("Engine", "LevelDBStore");
            this.Path = section.GetValue("Path", "Data_LevelDB_{0}");
        }
```

**Comment by hal0x2328** [comment]
This is causing issues for people trying to test RC1 by following the solo consensus node tutorial: https://docs.neo.org/v3/docs/en-us/develop/network/private-chain/solo.html

If they follow the tutorial in order, they will first create a wallet before setting the config.json values. 

So after they have done that, there will be a `Data_LevelDB_{0}` folder initialized with the magic number 5195086. 

Then when they use the provided config example with their new public key and restart neo-cli, they will try to access the same LevelDB folder only with the magic number 5309138 (or a different one if they changed it). 

So neo-cli will start consensus in WatchOnly mode and never start producing blocks.

**Comment by shargon** [comment]
Old, if remains, please re-open
