### ISSUE TITLE
show state immediately after neo-node start error

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-node#762]
![693f6484b79cc5ba0e9412e90545b98](https://user-images.githubusercontent.com/34291844/111279077-4319ec00-8675-11eb-885c-f6c0c10a59a3.png)

![a806ba04ee24181d0d74fe57bd80fbf](https://user-images.githubusercontent.com/34291844/111279259-7a889880-8675-11eb-8873-feb873b71bc6.png)

It is caused by the change https://github.com/neo-project/neo-node/pull/758, localnode is null at this time.

after several seconds later, it shows numbers.

**Comment by shargon** [comment]
Revert #758?

**Comment by ZhangTao1596** [comment]
> Revert #758?

If you have better solution to solve https://github.com/neo-project/neo/issues/2380.
I found that if you start node with websockt port occupied by another application, you will get different localnodes before and after call `NeoSystem.StartNode`.
