### ISSUE TITLE
node: Mac need long time to exit when connect RC1 testnet.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-node#770]
Mac need long time to exit when connecting RC1 testnet.

1. Download RC1 Mac version: https://github.com/neo-project/neo-node/releases/download/v3.0.0-rc1/neo-cli-osx-x64.zip
2. Run it, wait for several seconds to ensure it has synced some height.
3. Input `exit`. (ctrl + c has the same effect)
![image](https://user-images.githubusercontent.com/38493437/115527052-44b58000-a2c3-11eb-95c3-6a253e48baa6.png)

Seems akka not disconnect at once but just wait. It can take about 3 minutes to exit in Mac. I haven't seen this issue on other OS like (win10, centOS7.6, unbuntu 16.04).
@erikzhang @shargon

**Comment by shargon** [comment]
This only happens with RC1?

**Comment by shargon** [comment]
Old, if remains, please re-open
