### ISSUE TITLE
Is there any way to listen to newly published blocks at neo?

### ISSUE THREAD

**Issue by gitloverr** [neo-project/neo-node#786]
hi everyone,

can I subscribe to a channel for listen the newly published block information via websocket or like this on NEO 2.12.2? (not http getblocksize method ) 

If yes, how can I do that?

Is there any way?

thank you

**Comment by roman-khimov** [comment]
NeoGo provides that via its notification subsystem: https://github.com/nspcc-dev/neo-go/blob/master-2.x/docs/notifications.md

**Comment by gsmachado** [comment]
@gitloverr 

So... one of the things we care about in the [neow3j project](https://neow3j.io) is that the library should be as "reactive" as possible. People should be able to "listen" to blocks, transactions, and other info, in an easy way. 😄  🙏 

In our [examples repo](https://github.com/neow3j/neow3j-examples-java/tree/master/neo-n3-examples) you can find relevant info to build backends or smart contracts, including "monitoring the chain".

You can check the following links to concrete examples:

- [neow3j reactive APIs](https://javadoc.io/static/io.neow3j/core/3.10.0/io/neow3j/protocol/rx/JsonRpc2_0Rx.html)
- [Example to subscribe to new blocks](https://github.com/neow3j/neow3j-examples-java/blob/master/neo-n3-examples/src/main/java/io/neow3j/examples/jsonrpc/SubscribeToNewBlocks.java)
- [Example to submit a transaction and "track" if the tx result](https://github.com/neow3j/neow3j-examples-java/blob/master/neo-n3-examples/src/main/java/io/neow3j/examples/contractinvoke/TransactionTracking.java)

If you need any help, [open an issue here](https://github.com/neow3j/neow3j/issues) or [open a discussion topic here](https://github.com/neow3j/neow3j/discussions). 🐈 

🚀
