### ISSUE TITLE
No need to create an address as default when creating a new wallet

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-node#814]
Someone just wants to create a wallet and import an existed privkey but has to delete the first address because it 's never used.

**Comment by Liaojinghui** [comment]
why not allowing them to create a wallet by importing a private key?

**Comment by Liaojinghui** [comment]
empty wallet just looks weird,,,,, though it is normal in real life.....

**Comment by Qiao-Jin** [comment]
Moreover it think it should be enabled to delete address from wallet

**Comment by roman-khimov** [comment]
> empty wallet just looks weird,,,,, though it is normal in real life.....

NeoGo allows to create empty wallet, that's what `wallet init` command does by default. Only with `-a` it actually also creates a new account.

> Moreover it think it should be enabled to delete address from wallet

Sure. `wallet remove` in NeoGo allows to do that.
