### ISSUE TITLE
node: AssemblyLoadContext.Default.Unloading might not be reliable for thorough disposition

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo-node#816]
In these lines we set up `Unloading` events which are executed when user closes neo-cli.

https://github.com/neo-project/neo-node/blob/7aa1e1610dc5c303bde92a1fc8ea3dd8df00dae7/Neo.ConsoleService/ConsoleServiceBase.cs#L273-L279

However there might be problems in this strategy. Unless user chooses to close cli by typing "exit" command, other ways such as directly clicking "close" button will leave only no more than 2 seconds for this event. That means, if disposition actions take longer than this time period, whole process will be shut down before everything disposed gracefully.

Currently there seems nothing that must be disposed before shutting down (even DB), but still this is some vulnerability easy to be neglected.

https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.AppDomain.ProcessExit)%3Bk(SolutionItemsProject)%3Bk(SolutionItemsProject)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=net-5.0

**Comment by shargon** [comment]
Old, if remains, please re-open
