### ISSUE TITLE
How am I supposed to use `invoke` to send a `JArray` object？

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo-node#821]
Hi there, i was trying to use the `invoke` command of the neo-cli to call a contract, but I found that the method parameter has to be passed as a JArray instance. Anyone can tell me how to pass this instance from the console? thank you very much.

```C#
private void OnInvokeCommand(UInt160 scriptHash, string operation, JArray contractParameters = null, UInt160 sender = null, UInt160[] signerAccounts = null, decimal maxGas = 20)
```

**Comment by cloud8little** [comment]
` invoke 0xfe9a5ebf1c74b24a20182e6bc58169d71d389e2c getInfo [{"type":"Hash160","value":"0x71a87191aef3fcf5e4441d791ded67ebab1aee7e"}]`
