### ISSUE TITLE
node: neo-cli v3.0.3 - parser improvements

### ISSUE THREAD

**Issue by vincentgeneste** [neo-project/neo-node#832]
1) When doing an invoke on neo-cli 3.0.3, if it requires sender but it's not passed, the error returned is 

`Error: Index was outside the bounds of the array.`

this could/should be more explicit and says that `sender` has to be passed maybe ?

2) When using the option `maxGas` on an invoke, the parser helper says it should be 

`invoke <scriptHash> <operation> [contractParameters=null] [sender=null] [signerAccounts=null] [maxGas=20]`

but if we pass only `invoke <scriptHash> <operation> [contractParameters=null] [sender=null] [maxGas=20]` (without `signerAccounts` as the helper says), it does not work and expects both `maxGas` and `signerAccounts`, which i don't think is normal.

**Comment by shargon** [comment]
Old, if remains, please re-open
