### ISSUE TITLE
node: neo-cli v3.0.3 - invoke type detection issue

### ISSUE THREAD

**Issue by vincentgeneste** [neo-project/neo-node#833]
When doing an invoke on neo-cli v3.0.3, the Integer type is not recognized properly:

`invoke 0x590635eaf2364ba03dade7ed9a54efa20d72eba9 setCustomFee [{"type":"Hash160","value":"b137c83610d3f0331a48d8d6283864120b4f23a1"},{"type":"Integer","value":300}]`

works and interprets correctly the value as 300, while

`invoke 0x590635eaf2364ba03dade7ed9a54efa20d72eba9 setCustomFee [{"type":"Hash160","value":"b137c83610d3f0331a48d8d6283864120b4f23a1"},{"type":"Integer","value":"300"}]`

doesnt work and converts literally `"300"` instead of detecting it as an integer. I would expect with a type field to have not to worry about this.

**Comment by ediopia** [comment]
It breaks if there are spaces in value of string type.
<img width="1106" alt="Screen Shot 2021-12-05 at 1 55 08 PM" src="https://user-images.githubusercontent.com/6670368/144765442-8e859d6b-8c9c-4fc7-892a-aeb655044390.png">

**Comment by shargon** [comment]
Old, if remains, please re-open
