### ISSUE TITLE
state height

### ISSUE THREAD

**Issue by versionCollector** [neo-project/neo-node#845]
Hello!
When I'm asking ```getstateheight``` method and in response i get
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockheight": 8496437,
        "stateheight": 6362340
    }
}
```
Is it a normal behavior that ```stateheight``` is lower than ```blockheight```? If its not how can I fix it?

**Comment by Liaojinghui** [comment]
Yes, it is normal.
