### ISSUE TITLE
node: macOs monterey support

### ISSUE THREAD

**Issue by ediopia** [neo-project/neo-node#858]
My neo-cli 3.1.0 is not working after I upgraded to Monterey.
<img width="520" alt="Screen Shot 2022-04-11 at 11 26 30 PM" src="https://user-images.githubusercontent.com/6670368/163738138-3ee6a62c-26be-4341-9728-b1db919c8567.png">

**Comment by Liaojinghui** [comment]
Are you running on Apple Silicon?

**Comment by ediopia** [comment]
> Are you running on Apple Silicon?

No. Intel
