### ISSUE TITLE
Mode System

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo-node#863]
**Summary or problem description**
While i was doing research with neo, sometimes i have to switch among `private network`, `public network`, and `testnetwork`, it annoies since everytime i make a switch, i have to change not only the configuration file of the neo-core, but also plugins **manually**. It would be great if i could save my current system setting as a mode  and load it later.

**Do you have any solution you want to propose?**
Add  a mode system, when user saves a mode, copy all of the config files in the system into the mode folder with each mode under a user specified name.    maybe as a plugin module

**Neo Version**
- Neo 3

**Where in the software does this update applies to?**
- CLI
- Plugins

**Comment by ixje** [comment]
@Liaojinghui is it actually completed?
